### ISSUE TITLE
[FEATURE 💡] Hamburger menu

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#1]
### Description

- Required Haburger menu for mobile devices
- Given is the hamburger menu of Real nike website
- Something similar is expected from the contributor
- The hamburger menu should be visible only in mobile devices 

### Screenshots

| Original | Expected |
|:-:|:-:|
| ![mobile](https://github.com/warmachine028/nike/assets/75939390/6d574ba5-b208-4f64-b59b-6bfaadda6864) | ![hamburger](https://github.com/warmachine028/nike/assets/75939390/5e3fd063-0383-4554-ad48-d7a966872f9b) |

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by CarlosEGCH** [comment]
Can you please assign this issue to me? I would like to implement this feature :)

**Comment by warmachine028** [comment]
Sure! Assigning you right away.

**Comment by warmachine028** [comment]
@CarlosEGCH What is the status of work?

**Comment by warmachine028** [comment]
@CarlosEGCH, at least communicate before unassigning yourself? Really unprofessional attitude

**Comment by FranDiSilvestro** [comment]
@warmachine028 I would love to help you with this as well if you can assign it to me

**Comment by warmachine028** [comment]
Yes, The hamburger menu is needed ASAP

**Comment by FranDiSilvestro** [comment]
I have to leave for today, I couldn't finish it on time

**Comment by warmachine028** [comment]
> I have to leave for today, I couldn't finish it on time

You can take your time, maybe a day or 2. You might be able to do it.

**Comment by mhamzanadeem** [comment]
can u assign this feature / issue to me .  I  may implement this feature .

**Comment by warmachine028** [comment]
Actually someone has done almost the work @mhamzanadeem, so I can't assign it to you right now
