### ISSUE TITLE
[FEATURE 💡] Some UI Improvements

### ISSUE THREAD

**Issue by Keshav-Aneja** [warmachine028/nike#103]
### Description

In the current Version there are some small UI things. I am listing some of the UI faults:

1) In large screen formats, the Heading in the Hero section has no padding in the left:
To be Fixed:
![UI fix](https://github.com/warmachine028/nike/assets/119158790/70d57137-7fd7-450e-9e77-5489e5a17a6d)

Fixed Changes:
![fixed](https://github.com/warmachine028/nike/assets/119158790/676e235b-b0e7-4dbf-8860-3c225960701f)

2) In the Mobile Version the stats are not looking great aligning at the start, that can be improved by centering them

To be Fixed:
![to be fixed](https://github.com/warmachine028/nike/assets/119158790/f0d75c4c-3e24-440a-9180-268165498d69)

Fixed Changes:
![mobile fix](https://github.com/warmachine028/nike/assets/119158790/67d3895b-9aea-4d75-af5c-f9f5aa7a64db)

3. The Current Hard Hover effect can be somewhat improved, shadows and border effects can be added to increase the interactivity experience.
![shadow](https://github.com/warmachine028/nike/assets/119158790/3eb0b724-107b-44fe-8a46-77886e49786c)

Please Assign the Issue To me.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
Sure go ahead with it

**Comment by warmachine028** [comment]
** @Keshav-Aneja make sure the changes you make dont break responsiveness of the UI for small and medium devices. This is very critical**
