### ISSUE TITLE
[FEATURE 💡] dark/light theme improvement

### ISSUE THREAD

**Issue by Famozzy** [warmachine028/nike#105]
### Description

- Inverted navbar background color theme (Picture 1, Picture 2)
- Some texts do not contrast when in a dark theme (Picture 3)
- Some UI doesn't have dark theme (Picture 4, Picture 5)
- Theme button icon only shows the same icon

I'm willing to work on it

### Screenshots

Picture 1 (light theme)
![image](https://github.com/warmachine028/nike/assets/41115929/4ae3e315-afe3-40af-b4a1-ced3a97b67d1)

Picture 2 (dark theme)
![image](https://github.com/warmachine028/nike/assets/41115929/a642dd29-8e3c-4548-9c05-c71e1d750f23)

Picture 3
![image](https://github.com/warmachine028/nike/assets/41115929/f2f142d7-b542-443d-b630-f5932d177405)

Picture 4
![image](https://github.com/warmachine028/nike/assets/41115929/bb471142-0aab-4c1a-a4dc-66204e54ba00)

Picture 5 (dark theme)
![image](https://github.com/warmachine028/nike/assets/41115929/444a2870-01cc-4ad2-81cf-b696e6568d7c)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
Assigning you, work on it
