### ISSUE TITLE
[FEATURE 💡] Carousel for Customers

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#111]
### Description

A carousal feature would be a nice addition to this project

- Add a carousel for the customer reviews
- Add more dummy reviews
- The carousel must rotate automatically initially
- Must have a pagination item at the bottom to pause and navigate next or previous reviews 
- Any animation would be nice

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/d1caa8bf-b566-4832-b316-8f54e68bc454)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by VadimDez** [comment]
Hey @warmachine028 can you assign this to me please?

**Comment by warmachine028** [comment]
Sure @VadimDez assigning you

**Comment by warmachine028** [comment]
@VadimDez what's the status?

**Comment by akash0708** [comment]
@warmachine028 I can work on this if it's alright with you.

**Comment by debajoti** [comment]
@warmachine028 Can I work on these?

**Comment by warmachine028** [comment]
@akash0708 , @debajoti both of you can work on this issue. Since the previous assignee has left this issue as stale. I would accept any of the PR's which are made first.
