### ISSUE TITLE
[FEATURE 💡] Menu needs changes

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#112]
### Description

- The menu must open over everything, including the navbar
- It also had a slight open animation before, it must be added again.

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/5c284f85-4eed-48f2-82ee-9c72ad0f569f)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by VadimDez** [comment]
@warmachine028  can.i give it a try?

**Comment by warmachine028** [comment]
Make sure to work on the issue on hand first, many contributors have the tendency to leave issues stale.

**Comment by akash0708** [comment]
Hey @warmachine028 I would love to work on this!

**Comment by warmachine028** [comment]
Sure
