### ISSUE TITLE
[FEATURE 💡] Make Navbar floating 

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#113]
### Description

- When we scroll down, the Navbar is not visible in the page
- Make the Icon a bit bigger
- Make the Navbar thinner than current
- Make the Navbar floating
- The floating Navbar should only be visible when scrolling up from anywhere it's not currently visible
- have a look at the [original website here](https://www.nike.com/sg/). Scroll down and observe the Navbar here

### Screenshots

- Original Website

![Screenshot_2023-10-05-19-51-17-658_com android chrome](https://github.com/warmachine028/nike/assets/75939390/91516dd8-5a6e-45fd-9662-9ef6bf7ef39f)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by theDevSoham** [comment]
Hello @warmachine028 I can work on this issue. Can you please assign me the task?

**Comment by warmachine028** [comment]
Alright assigning you

**Comment by warmachine028** [comment]
@theDevSoham what's the status of work?

**Comment by theDevSoham** [comment]
@warmachine028 pretty much done...testing
