### ISSUE TITLE
[BUG 🐞] Scrolling disabled

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#119]
### Description

- Can't scroll the site in mobile view. 
- Please look into this issue and fix it without losing any functionality.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by dylanbuchi** [comment]
Hi @warmachine028, could you assign me this issue, please?

**Comment by Pinaka-Pani-18** [comment]
Hi , Can I work on this issue ?

**Comment by warmachine028** [comment]
@dylanbuchi , @Pinaka-Pani-18 assigning you both. Contributors leave issues at stale.

**Comment by Pinaka-Pani-18** [comment]
@warmachine028, I am able to scroll in the mobile view. Could you please check it once? If the issue there, could you record a video that shows the problem?

**Comment by warmachine028** [comment]
> @warmachine028, I am able to scroll in the mobile view. Could you please check it once? If the issue there, could you record a video that shows the problem?

Can you scroll in a real mobile too? I am unable to do that

**Comment by warmachine028** [comment]
@dylanbuchi can you scroll in mobile View?

**Comment by Pinaka-Pani-18** [comment]
> > @warmachine028, I am able to scroll in the mobile view. Could you please check it once? If the issue there, could you record a video that shows the problem?
> 
> Can you scroll in a real mobile too? I am unable to do that

No, I'm sorry, I checked it in mobile view in desktop, but on a real mobile device, it's not scrolling. I'll fix it.

**Comment by warmachine028** [comment]
Yes, please try. It's a major issue
