### ISSUE TITLE
[FEATURE 💡] Designing of buttons

### ISSUE THREAD

**Issue by divyanshiet** [warmachine028/nike#124]
### Description

Hey, I would like to add some styling, and animations in the buttons on the webpage such that, it makes the website more responsive and attractive. Will love to work on this kindly assign it to me with hacktoberfest label.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by ayush6678** [comment]
Hey @divyanshiet I would like to work on this issue. Can you assign this issue to me?

**Comment by swaleha2002** [comment]
Hi @divyanshiet,

I'm excited about the opportunity to enhance the styling and animations for the buttons on the webpage! I believe this will significantly improve the website's responsiveness and overall attractiveness.

I would like to take on this task and contribute to the project. Could you please assign this issue to me.

Looking forward to working on this!

**Comment by abdulrehmanjaved-1** [comment]
Hey! I want to make this kind of small improvements in nike. Thanks

**Comment by warmachine028** [comment]
@divyanshiet work on this

**Comment by warmachine028** [comment]
@divyanshiet are you working on this? Other contributors are in queue too

**Comment by divyanshiet** [comment]
> @divyanshiet are you working on this? Other contributors are in queue too

yes currently trying to figure out issue it's has some error while running locally

**Comment by divyanshiet** [comment]
> @divyanshiet are you working on this? Other contributors are in queue too

you may assign it to others, it is showing a "model not found" error when I try to run it locally.

**Comment by abdulrehmanjaved-1** [comment]
Assign me bro

**Comment by warmachine028** [comment]
@abdulrehmanjaved-1 make sure to pull the latest changes in your Fork before starting this issue.
