### ISSUE TITLE
[FEATURE 💡] Cart Functionality 

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#127]
### Description

Add cart Functionality to the website. Use dummy json data for reference

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
can we do something with local data and then local storage seems to be the only solution now.

**Comment by IrfanSalim** [comment]
yes sure, do you have any dummy data?

**Comment by warmachine028** [comment]
Can you create a dummy data for now.

**Comment by IrfanSalim** [comment]
cool, please assign
