### ISSUE TITLE
[FEATURE 💡] SignIn/SignUp

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#128]
### Description

- Add signin, Signup functionality for the users.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by KriteshTimsina** [comment]
Assign me !

**Comment by warmachine028** [comment]
assigning

**Comment by KriteshTimsina** [comment]
Haven't got chance to work on it due to personal reasons. Will update you asap

**Comment by warmachine028** [comment]
No problem, take your time

**Comment by KriteshTimsina** [comment]
How am I supposed to achieve this functionality? Do you just need the UI ?

**Comment by warmachine028** [comment]
Currently the UI will do fine, make 2 seperate routes, sign in and sign up
