### ISSUE TITLE
[FEATURE 💡] Create a Single Product Component and Page

### ISSUE THREAD

**Issue by sushilmagare10** [warmachine028/nike#133]
### Description

Currently we can only see the products but we should have a single product page which is selected so we can see & select sizes, color, etc before adding to cart...

I can work on this please assign me this feature...

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
@sushilmagare10 please start working on it. Assigning you

**Comment by warmachine028** [comment]
Have you started working on it?

**Comment by sushilmagare10** [comment]
Yes I have @warmachine028

**Comment by warmachine028** [comment]
Good Good

**Comment by sushilmagare10** [comment]
can we use a fake api for products @warmachine028

**Comment by warmachine028** [comment]
Could you elaborate more on fake api?

**Comment by sushilmagare10** [comment]
can cant get the specific products as we are using dummy data .. we need the id to a specific product but we cant do it with what we have... @warmachine028 

eg:  ```
 useEffect(() => {
    const getProduct = async () => {
      try {
        const res = await userRequest.get("/product/" + id);
        setProduct(res.data.product);
      } catch {}
    };
    getProduct();
  }, [id]);
```

**Comment by warmachine028** [comment]
Add the changes in the dummy data and proceed. You can add the I'd field

**Comment by warmachine028** [comment]
You are working on it right?

**Comment by hanzalahwaheed** [comment]
@warmachine028 Please assign this to me! I will work on it.
