### ISSUE TITLE
[FEATURE 💡] Interactive Cards

### ISSUE THREAD

**Issue by FabianCristancho** [warmachine028/nike#135]
### Description

I would like to work in cards, in order to make them more interactive and that this is a plus for the user to be more comfortable.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by maazshakeel** [comment]
Can I work on this issue, Fabian? (Although, can you clarify a bit more about interactiveness you want? [Like: hover effects, cursor pointer...])

**Comment by VishalMyla** [comment]
Please assign this issue to me

**Comment by warmachine028** [comment]
@FabianCristancho Do you want to work on this or you are raising PR for other's?

**Comment by FabianCristancho** [comment]
I would like to work It 🫡

**Comment by warmachine028** [comment]
Please work on it, I'm assigning you

**Comment by warmachine028** [comment]
@FabianCristancho what's the status?

**Comment by FabianCristancho** [comment]
@warmachine028 I'm working still. I am adding moving to the cards and some shadow

**Comment by warmachine028** [comment]
Alright work on it @FabianCristancho

**Comment by warmachine028** [comment]
@FabianCristancho what's the status on this?

**Comment by FabianCristancho** [comment]
@warmachine028 it's about 60%. Sorry for delay, but at the moment I am in exams :(

**Comment by FabianCristancho** [comment]
ok, sure @warmachine028

**Comment by FabianCristancho** [comment]
I appreciate so much if you accept this feature in order to participate in Hacktoberfest
