### ISSUE TITLE
[BUG 🐞] Product Cart Visibility

### ISSUE THREAD

**Issue by MaximilianoCabreraP** [warmachine028/nike#136]
### Description

When you click in Cart Icon its show you the Cartview, but when you click it again, nothing happends.

(I worked on it before the Issue report, sorry for than! here is my [PR](https://github.com/warmachine028/nike/pull/129), if ok, you can assign it to me?)

### Screenshots

![image](https://github.com/warmachine028/nike/assets/39493720/a958c7cb-89a2-4c6e-ba5f-b0e3760ede93)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
@MaximilianoCabreraP Sure, Ill assign you to this. I can understand your concern regarding raising an issue.
