### ISSUE TITLE
[FEATURE 💡] Update Cart items 

### ISSUE THREAD

**Issue by IrfanSalim** [warmachine028/nike#137]
### Description

Cart functionality to reduce the quantity or remove an item 

### Screenshots

![image](https://github.com/warmachine028/nike/assets/109443065/793f2fb5-f323-4b56-bebb-0a514cff5fad)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by IrfanSalim** [comment]
Please assign @warmachine028

**Comment by warmachine028** [comment]
assigned
