### ISSUE TITLE
[FEATURE 💡] Element Changing Positions

### ISSUE THREAD

**Issue by Bikalpa-Paudel** [warmachine028/nike#140]
### Description

In the section labeled **"What Our Customers Say?"**, there is a noticeable change in the layout of elements when longer text feedback is provided. Specifically, the elements shift downward to accommodate the longer text.

This change can impact the overall user experience because it may cause users to have to scroll down for arrow clicking. It affects all the elements below them as well.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Bikalpa-Paudel** [comment]
I would like to solve this issue.

**Comment by warmachine028** [comment]
@Bikalpa-Paudel what is the status

**Comment by Bikalpa-Paudel** [comment]
![image](https://github.com/warmachine028/nike/assets/89839823/36eb1420-810c-42e3-8f03-d48c43c8d3c2)
I have added a view more option

Do you think it's looking good? If you think it's good I'll send a PR

**Comment by warmachine028** [comment]
Looks good, create A pr. If something looks incorrect in the preview generated in Vercel I'll add a review for changes

**Comment by warmachine028** [comment]
Merge the latest changes from main and start working on it asap

**Comment by hanzalahwaheed** [comment]
@Bikalpa-Paudel Hii! Please check the current version of the app. This is because even I tried to address this problem and made some changes for Issue #162
Thanks!

**Comment by Bikalpa-Paudel** [comment]
#165
