### ISSUE TITLE
[BUG 🐞] Navbar not working

### ISSUE THREAD

**Issue by abdulrehmanjaved-1** [warmachine028/nike#142]
### Description

If we click to check carts, from there we cannot go to other components using Navbar options.

Steps to reproduce:
->Go to carts.
->Click on any navbar option.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by abdulrehmanjaved-1** [comment]
I will work on this issue.
Assign bro.

**Comment by warmachine028** [comment]
Screenshot not visible

**Comment by abdulrehmanjaved-1** [comment]
PNG Not uploading I don't why.
but i have updated the description.
Also steps mention to reproduce.
