### ISSUE TITLE
[BUG 🐞] Add Spacing for "Your Cart" text 

### ISSUE THREAD

**Issue by leonyangela** [warmachine028/nike#143]
### Description

Adding space for padding top on "Your Cart" page so it doesn't cut off

### Screenshots

<img width="960" alt="image" src="https://github.com/warmachine028/nike/assets/38250310/b8423082-d427-43d0-94ae-d1eb13120937">

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by leonyangela** [comment]
Hi, can you please assign me for this? Thanks

**Comment by shyam1112** [comment]
@leonyangela can you assign this task to me

**Comment by warmachine028** [comment]
Assigned @leonyangela
