### ISSUE TITLE
[BUG 🐞] Enhancements to Contact Information Footer (Email and Phone Number)

### ISSUE THREAD

**Issue by leonyangela** [warmachine028/nike#147]
### Description

Reproduce the issue: 
"Get in touch" footer links for clicking email or phone didn't open email or phone, but instead, it scrolled to the top of the page. 
I'd like to make if user clicking email or phone links opens the corresponding app.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by vishisht-dubey** [comment]
Hiii @leonyangela I am working on this issue please assign this to me

**Comment by leonyangela** [comment]
Hi @vishisht-dubey I have done it and made a PR, this issues should be closed. thanks

**Comment by warmachine028** [comment]
@leonyangela i have Assigned you

**Comment by leonyangela** [comment]
Hi @warmachine028, thank you, I have made a PR for this on this link(https://github.com/warmachine028/nike/pull/148)

**Comment by warmachine028** [comment]
I will be reviewing your PR asap, please read the Pinned issue for the delay

**Comment by warmachine028** [comment]
@leonyangela make the necessary changes
