### ISSUE TITLE
[FEATURE 💡] Improve Testimonials

### ISSUE THREAD

**Issue by hanzalahwaheed** [warmachine028/nike#152]
### Description

A smooth transition (like a fade effect can be added) to the testimonials section to further improve the aesthetics of the website.

### Screenshots

[Screencast from 2023-10-15 14-00-32.webm](https://github.com/warmachine028/nike/assets/101456741/f0af7a3f-99af-415c-926b-3256792904f7)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by hanzalahwaheed** [comment]
Can I be assigned to work on this (if deemed necessary) under Hacktoberfest please.

**Comment by warmachine028** [comment]
@hanzalahwaheed work on it

**Comment by AbdullahTheDev** [comment]
Can you assign this task to me under Hacktoberfest?

**Comment by warmachine028** [comment]
Assigned @hanzalahwaheed

**Comment by hanzalahwaheed** [comment]
@warmachine028 I have completed this task but not able to create a PR. I will wait for your reply.
