### ISSUE TITLE
[BUG 🐞] Outdated Twitter Logo

### ISSUE THREAD

**Issue by hanzalahwaheed** [warmachine028/nike#154]
### Description

The Twitter logo needs to to be updated to X.

### Screenshots

![image](https://github.com/warmachine028/nike/assets/101456741/ba011bd0-60b1-4adb-946b-d1fcb4a12dd8)

**Comment by hanzalahwaheed** [comment]
Please assign this to me under Hacktoberfest.

**Comment by Aabiskar-dhenga** [comment]
@warmachine028  hey brother , I have create the Pr please look over it and provide feedback to me

**Comment by Shashankpantiitbhilai** [comment]
please assign this to me

**Comment by warmachine028** [comment]
@Shashankpantiitbhilai i have already Assigned someone
