### ISSUE TITLE
[BUG 🐞] Cart Button looks ugly

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#160]
### Description

- This card button on mobile view doesn't look good
- Make it smaller

### Screenshots

![Screenshot_2023-10-17-07-03-38-930_com android chrome](https://github.com/warmachine028/nike/assets/75939390/f0ebb2de-42c1-4622-8814-3dc65a715751)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by AnsellMaximilian** [comment]
Hey, @warmachine028, I can give this a try.

**Comment by warmachine028** [comment]
@AnsellMaximilian work on it

**Comment by AnsellMaximilian** [comment]
Thanks. If you wouldn't mind, could you add the `hacktoberfest-accepted` label on this issue.

**Comment by warmachine028** [comment]
We add hacktoberfest-accepted labels only on PRs which are ready for merge after successful reviewing
