### ISSUE TITLE
[FEATURE 💡] Implement Search Bar functionality for Mobile Devices

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#163]
### Description

- Add a Search Bar functionality.
- When User clicks magnifying icon, this search must be overlayed.
- Show results while typing/
- Take ideas from [here](https://www.nike.com/in)

### Screenshots

- Mobile Search Bar
![image](https://github.com/warmachine028/nike/assets/75939390/af32c025-0ba3-4134-ad44-973be1e9c0fd)

- Desktop Search Bar
![image](https://github.com/warmachine028/nike/assets/75939390/3b2a5995-1090-48b8-80a1-35d47e6b6572)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Mithilesh-create** [comment]
I would like to work on this issue .

**Comment by warmachine028** [comment]
@Mithilesh-create start working on this

**Comment by KriteshTimsina** [comment]
Assign me!

**Comment by warmachine028** [comment]
@KriteshTimsina what's the status on this

**Comment by KriteshTimsina** [comment]
Working on it. Kinda busy these days

**Comment by warmachine028** [comment]
Will you be able to complete this before 31st october?

**Comment by KriteshTimsina** [comment]
I don't think I can. You can assign it to someone else.

**Comment by ashish07-07** [comment]
hey i will try to work on this today

**Comment by warmachine028** [comment]
Work on it

**Comment by ashish07-07** [comment]
i had got dependency warning as i used onChange function because of loopy rendering its giving me an error .

**Comment by warmachine028** [comment]
Show the error and warning

**Comment by DhruvGahoi** [comment]
@warmachine028 is this issue opened yet ?

**Comment by warmachine028** [comment]
Yes it is

**Comment by DhruvGahoi** [comment]
@warmachine028 okay I'm gonna start working on this soon.

**Comment by warmachine028** [comment]
Sure

**Comment by Abhiraj-Sardar** [comment]
@warmachine028 
can you assign it to me?

**Comment by DhruvGahoi** [comment]
@warmachine028 Actually I just wanted to know you want this functionality for both mobile and desktop, cause in the issue you mentioned implementing for the mobile view ?

**Comment by warmachine028** [comment]
Don't spoil the existing functionality for desktops. Implement the mobile only. If you can implement for both at once that's even better

**Comment by DhruvGahoi** [comment]
@warmachine028 I have implemented the functionality for both mobile and desktop view, I just wanted to know what results should I have to show while typing, like did you mean Debouncing ?

**Comment by warmachine028** [comment]
For now display a list of dummy links with #

**Comment by DhruvGahoi** [comment]
@warmachine028 can you review this PR?
