### ISSUE TITLE
[BUG 🐞] Navbar overlaps Cart in Mobile View

### ISSUE THREAD

**Issue by hanzalahwaheed** [warmachine028/nike#164]
### Description

The "Your Cart" heading is hidden due to the Navbar on the the Cart Page.

### Screenshots

![image](https://github.com/warmachine028/nike/assets/101456741/27be5d3f-001f-4803-aade-6ed7d7d6f225)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by hanzalahwaheed** [comment]
@warmachine028 Please assign this to me under Hacktoberfest. Thank You!

**Comment by Ferdinand-Ogama** [comment]
Kindly assign this to me.

**Comment by Petsamuel** [comment]
kindly assign this to me

**Comment by warmachine028** [comment]
@hanzalahwaheed please add some spacing from the top. Assigning you
