### ISSUE TITLE
[BUG 🐞] Cart Add or Subtract Item

### ISSUE THREAD

**Issue by hanzalahwaheed** [warmachine028/nike#171]
### Description

Both the '-' and the 'x' buttons reduce the item in the cart. I believe the buttons should be '-' and '+' instead. 

### Screenshots

Here, both - and x subtract the item from the cart.

[Screencast from 2023-10-19 13-29-29.webm](https://github.com/warmachine028/nike/assets/101456741/e689c60d-cf9e-4efe-a0f2-eeb1cbe30eb5)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by hanzalahwaheed** [comment]
Please assign this task to me. Thank You!

**Comment by warmachine028** [comment]
@hanzalahwaheed, Shoaib has already made a PR in this issue, so I am assigning him in it. I have seen your enthusiasm in the recent Contributions you have made towards this project. Keep it up!

**Comment by warmachine028** [comment]
@shoaib-31 please read contributing guidelines before making a PR. This is not how contributions work in this project. You must ask to get assigned to an issue, before starting the work

**Comment by hanzalahwaheed** [comment]
> @hanzalahwaheed, @shoaib-31 has already made a PR in this issue, so I am assigning him in it. I have seen your enthusiasm in the recent Contributions you have made towards this project. Keep it up!

Yes it's fine as I was aiming to get my Hactoberfest PRs done! I'll keep contributing to the project and try to make improvements here and there!

**Comment by warmachine028** [comment]
@shoaib-31 please ask here to get assigned so that I can assign you this issue.

**Comment by shoaib-31** [comment]
@warmachine028 I will be pleased to be assigned. I will resolve the conflicts within an hour or two and will make a commit soon.

**Comment by warmachine028** [comment]
Great, assigning you right away @shoaib-31

**Comment by shoaib-31** [comment]
@warmachine028 , please take a look on this PR.
