### ISSUE TITLE
[FEATURE 💡] Snackbar notifications

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#177]
### Description

+ Add snackbar notifications instead of this dialog box after adding an item to cart

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/fabba1a6-b282-45d9-9e02-a27aefb932fa)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
@shoaib-31 Sure, assigning you. But make 2 seperate PR's. as you are already assigned to another issue

**Comment by shoaib-31** [comment]
@warmachine028 Take a look, is this okay?
[video.webm](https://github.com/warmachine028/nike/assets/103197883/eebe9051-1bb6-4881-b668-478e092a56c5)
