### ISSUE TITLE
[FEATURE 💡] View Details Page

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#18]
### Description

- View Details Page Needs to be designed for `Nike`.
- An example details page has been provided below for reference

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/c2ff68df-7dc1-48cd-b461-23b5212f53ce)

![image](https://github.com/warmachine028/nike/assets/75939390/cd24b6c4-53ab-431e-9882-c6f401ecd1d2)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by mhamzanadeem** [comment]
In this feature/ isssue ,  we have to make a page like this ??

![7787](https://github.com/warmachine028/nike/assets/114602354/89ef7d49-33d2-4d98-994d-4f33f7a3182e)

**Comment by mhamzanadeem** [comment]
In this feature / issue ,  We have to make a page(when a User click on View Details button , this page should open) like this ?
![78787](https://github.com/warmachine028/nike/assets/114602354/14dff678-31fa-4677-b962-671dbcd5faad)

**Comment by warmachine028** [comment]
Yes, this page should open. Would it require routing? 
If yes, please use react-router

**Comment by mhamzanadeem** [comment]
> * Yes, this page should open. Would it require routing?
> * If yes, please use react-router.
> * Also, you don't need to necessarily copy the design, you can if you want, but there's room for putting your own creative ideas too with this being a reference point.
> * Let me know if you want to get assigned here 🥂.

I will let you know when i want to get assigned on this issue

**Comment by mhamzanadeem** [comment]
Can u tell me where i can get the pic of big shoe(which is black and yellow in color) in repository?

**Comment by warmachine028** [comment]
> > * Yes, this page should open. Would it require routing?
> > * If yes, please use react-router.
> > * Also, you don't need to necessarily copy the design, you can if you want, but there's room for putting your own creative ideas too with this being a reference point.
> > * Let me know if you want to get assigned here 🥂.
> 
> I will let you know when i want to get assigned on this issue

Alright 👍

**Comment by warmachine028** [comment]
> Can u tell me where i can get the pic of big shoe(which is black and yellow in color) in repository?

This particular image is taken as a reference, but other shoe images are stored inside `src/assets/images`

**Comment by bubbster95** [comment]
Can I take a crack at this?  @mhamzanadeem @warmachine028

**Comment by hamzapaskingakhtar1999** [comment]
This is only for view details button leading to a new page. Not for individual shoes?

Also do you need the shoes to change color according to the color that is selected?

**Comment by warmachine028** [comment]
No just make the page, right now for view Details

**Comment by deeksharungta** [comment]
hey, i would like to work on this issue. Could you please assign it to me?

**Comment by warmachine028** [comment]
> hey, I would like to work on this issue. Could you please assign it to me?

Alright assigning you

**Comment by deeksharungta** [comment]
Hey @warmachine028, I won't be able to work on the issue for a few days, so I'm unassigning myself from the issue so that you can assign it to someone else.

**Comment by vaqueraoscar0** [comment]
Hi, i’d like to take on this issue if possible, mind if you assign me.

**Comment by hamzapaskingakhtar1999** [comment]
Wouldn't it be best if anyone can work on it. Fork it and whoever submits a pull request. Review it and merge it?
