### ISSUE TITLE
Readme File can be modified 

### ISSUE THREAD

**Issue by Tushar2930** [warmachine028/nike#189]
### Description

Readme file can be made more descriptive and contribution part can be made more detailed

**Comment by warmachine028** [comment]
Start working on it, but make 2 seperate PR's

**Comment by eshan-one** [comment]
Hi @warmachine028 can you assign me this issue? I have already worked on this project as this from JavaScript Mastery. I want to help you build your Readme.md file. Check my site:  https://eshans-pro-store.netlify.app/
