### ISSUE TITLE
[BUG 🐞] About us link not found in footer

### ISSUE THREAD

**Issue by Tushar2930** [warmachine028/nike#190]
### Description

The about us link does not navigate to some url rarther it reloads the page 

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Virtual4087** [comment]
I can work on this. Can you assign me?

**Comment by warmachine028** [comment]
@Tushar2930 assigned you

**Comment by Nikhilh26** [comment]
Assign this to me
