### ISSUE TITLE
[FEATURE] Hover Effects

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#2]
### Description

- Add Hover Effects to buttons
- The buttons must have primary color on Hover (white)
- Must have border color as background Color 
- Text color must be same as border color

### Screenshots
Similar to this 
![Screenshot_2023-08-25-09-39-13-106_com android chrome](https://github.com/warmachine028/nike/assets/75939390/33c69ca6-3ae9-40c3-99d1-4002392dc564)

### Additional information

- Implement it using tailwindCSS
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by AdityaAB4** [comment]
Hello, I want to work on this issue.

**Comment by warmachine028** [comment]
Sure! Assigning you

**Comment by warmachine028** [comment]
If you liked contributing to this Project, please leave a star.
