### ISSUE TITLE
[BUG]: Remove title Padding from Hero Section

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#26]
### Description

- The title in the hero section has some unwanted padding attached to it.
- This needs to be removed from the hero section
- Change the Hero section from previous to the given code below.

```jsx
<section className="xl:padding-l wide:padding-r padding-b">
  <div id="home" className="w-full flex xl:flex-row flex-col justify-center min-h-screen gap-10 max-container">
    <div className="relative xl:w-2/5 flex flex-col justify-center items-start w-full max-xl:padding-x pt-28">
      <h1 className="mt-10 font-palanquin text-8xl max-sm:text-[72px] max-sm:leading-[82px] font-bold">
        <span className="xl:bg-white xl:whitespace-nowrap relative z-10 pr-10 dark:bg-slate-gray duration-300 rounded-lg">The New Arrival</span>
	<br />
        <span className="text-coral-red inline-block mt-3">Nike </span> Shoes
      </h1>
...
```

### Screenshots

| Mobile | Desktop |
|:--:|:--:|
|![mobile](https://github.com/warmachine028/nike/assets/75939390/38cd3a92-5fbc-423d-ac3f-807a827de650) | ![image](https://github.com/warmachine028/nike/assets/75939390/d52d4049-50fc-4cc8-abf1-d9b7ae706e80) |

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by MS07062000** [comment]
May I know which padding you want to remove or reduce, like top, bottom, left, or right?

**Comment by warmachine028** [comment]
Can you see the padding before the word `The` in the title, I want to remove that

**Comment by mhamzanadeem** [comment]
can i contibute to it ?

**Comment by warmachine028** [comment]
Yes, assigning you

**Comment by mhamzanadeem** [comment]
I have fix the issue .
![Screenshot 2023-09-09 005719](https://github.com/warmachine028/nike/assets/114602354/da3d29de-05b0-43b6-aa72-b1ee5b11ced6)

can u assign me the issue . So that i can do pull request.

**Comment by warmachine028** [comment]
You can make the PR now! go Ahead
