### ISSUE TITLE
[OTHER] Improve SEO and Accessibility 

### ISSUE THREAD

**Issue by Sky-De** [warmachine028/nike#287]
### Improve SEO and Accessibility
Currently based on the _Lighthouse_ report Accessibility is 96% and SEO is 80% that is good but these can be 100% for maximum technical search engine results

 [x]  improve Accessibility to 100%
 [x]  improve SEO to 100%
 [x]  I will address this issue

![Screenshot 2024-02-28 143410](https://github.com/warmachine028/nike/assets/79264045/b1124e63-2ba7-42bf-8a9e-c72faf50dd7e)

**Comment by Sky-De** [comment]
@warmachine028 hi there, I had some work on this project before and just now I took a look and found this issue, please assign this to me, I would like to fix it , thanks

**Comment by warmachine028** [comment]
Ok sure work on it

**Comment by Sky-De** [comment]
@warmachine028 I have to add links to social media in the footer, It can be done by just adding an empty string as a URL, but I want to ask if you have those links, share them with me and i put them there otherwise i can just add "" for them, in both cases issue related to "
Links are not crawlable" will be fixed but it is better practice to add real URLs there
![Screenshot 2024-02-29 020016](https://github.com/warmachine028/nike/assets/79264045/db7e17ad-0a61-4f51-b722-8f1a380c41b8)

inform me about it
also the live URL of this app dose not load for me, do you have the same problem?

**Comment by warmachine028** [comment]
Can you add urls for example.com only for now since the social media pages are not real

**Comment by Sky-De** [comment]
@warmachine028 hi there, this is done, please close this issue
Thanks
