### ISSUE TITLE
[FEATURE] Dark Mode

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#3]
### Description

- Implement Dark theme using Context in react.
- User can select using a toggle similar to **[memories](https://memories-pritam.vercel.app)** or a drop down. 
- Use TailwindCSS for implementing this feature.
- Existing appearance on default mode must not be hampered at any cost.
- The toggle must be present on the sidebar for Mobile devices.
- **Discuss your approach with the maintainer thoroughly before getting assigned to this issue**.

### Additional information

- Avoid PropDrilling
- Avoid using CSS directly
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by jakepears** [comment]
you can assign this to me and i'll implement a dark mode

**Comment by warmachine028** [comment]
Sure, assigning you

**Comment by warmachine028** [comment]
What's the status?

**Comment by jakepears** [comment]
Sorry I forgot about it, I'll start working and it'll be done within the next few days.

**Comment by warmachine028** [comment]
It's alright, happens. Just start working whenever you're available

**Comment by warmachine028** [comment]
## Great Job! Merged into main.
Make sure to start this repo ⭐⭐.
