### ISSUE TITLE
[BUG 🐞] Theme switch Fixes

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#30]
### Description

- The theme button on the navbar becomes invisible on switching to dark mode.
- Also make it cursor-pointer to make it more visible.
- This issue needs to be fixed.

### Screenshots

| Light Mode | Dark Mode |
|:--:|:--:|
|![image](https://github.com/warmachine028/nike/assets/75939390/c9a317df-4f03-4e16-b91c-056bbd56c140)|![image](https://github.com/warmachine028/nike/assets/75939390/8facf0a6-75cd-4c36-8605-c744ed351335) |

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by FranDiSilvestro** [comment]
Hi! I want this to be my first contribution, can u assign me please?

**Comment by warmachine028** [comment]
Great! Assigning you right away.

**Comment by FranDiSilvestro** [comment]
Hi, I fixed the issue (Pull request #35 )
