### ISSUE TITLE
[BUG 🐞]  Customer Review UI , padding not implement properly 

### ISSUE THREAD

**Issue by Piyush-linux** [warmachine028/nike#305]
### Description

The UI of Customer review lack little improvements like
- [ ] border radius
- [ ] proper padding

### Screenshots

![Screenshot_2024-03-15-13-40-47_1920x1080](https://github.com/warmachine028/nike/assets/72852842/f61a0ce0-6f35-4bb4-8930-ec058982397a)

### Additional information

I've stared as well as forked this Repo , Please assign me this issue so I can Start working on the  too !

**Comment by warmachine028** [comment]
fix this @Piyush-linux

**Comment by Piyush-linux** [comment]
Need Help , **Husky showing Error** @warmachine028 
- I created a branch and changed the require file only
- didn't touch files related to husky and other

![Screenshot_2024-03-16-10-18-06_1920x1080](https://github.com/warmachine028/nike/assets/72852842/f62db628-6748-46a7-a720-b14ed2668860)

**Comment by warmachine028** [comment]
Could you just comment out the husky file contents for now
