### ISSUE TITLE
[BUG 🐞] Sign Up Input

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#31]
### Description

- The sign up input doesn't feel accurate on dark modes.
- This needs to match the theme.

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/c153564e-33dd-440d-b281-d36d739af69b)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by S1ddG** [comment]
Hi @warmachine028 can you assign this issue to me?

**Comment by warmachine028** [comment]
Sure! Assigning you

**Comment by mhamzanadeem** [comment]
![7787](https://github.com/warmachine028/nike/assets/114602354/03f7e0d0-5a23-4241-88dd-2f2a74f2dc1f)

I have fixed the issue . can u assign me

**Comment by warmachine028** [comment]
@mhamzanadeem I have already assigned this issue to @S1ddG , Issues get assigned in first-come-first-serve basis. But if he is unable to solve it, you will get it assigned.

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem I have already assigned this issue to @S1ddG , Issues get assigned in first-come-first-serve basis. But if he is unable to solve it, you will get it assigned.

Has anybody solved this issue ?  can you assign me this issue ?

**Comment by warmachine028** [comment]
I am assigning you both, if you solve it first the issue will be closed
