### ISSUE TITLE
[BUG 🐞] Page title is overlayed

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#32]
### Description

- The page title of Hero Section is not properly visible in mobile devices.
- This needs to be fixed.

### Screenshots

![mobile](https://github.com/warmachine028/nike/assets/75939390/42c3de2a-0be4-4b44-8fba-86908374695e)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by mhamzanadeem** [comment]
Hi, 
I just changed the font size in media query .  now it is correct ?

![mobile](https://github.com/warmachine028/nike/assets/114602354/642bede5-3868-4357-9c7f-b03e2573ab50)

**Comment by warmachine028** [comment]
I guess changing the media queries won't help in this case, we need to do something for the z axis somehow

**Comment by mhamzanadeem** [comment]
![mobile](https://github.com/warmachine028/nike/assets/114602354/3778e2c5-b7bb-48a7-8e58-2834ceb07cfa)

I have fixed the issue.  Can u assign this issue to me.

**Comment by warmachine028** [comment]
Assigning you
