### ISSUE TITLE
[BUG 🐞] Streched favicon

### ISSUE THREAD

**Issue by FranDiSilvestro** [warmachine028/nike#36]
### Description

Favicon is disproportionate

### Screenshots

![image](https://github.com/warmachine028/nike/assets/107486053/21114229-8dd0-47bd-a008-0919849747cb)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
Assigning you

**Comment by FranDiSilvestro** [comment]
Done :), i will now work on the hamburger menu
