### ISSUE TITLE
[FEATURE 💡] Text selection color blue is not matching with website theme.

### ISSUE THREAD

**Issue by CodeTorso** [warmachine028/nike#39]
### Description

The website has this orange-black theme.

Not perfectly matched with the blue selection colour.

I can change that to yellow or even light orange which will look a lot better.

Also it would be nice if we selecting images is disabled

### Screenshots

<img width="1080" alt="Screenshot 2023-09-10 012326" src="https://github.com/warmachine028/nike/assets/129188028/75ba8f21-0d7f-482b-94cc-e3be2a35ab81">

**Comment by warmachine028** [comment]
# Hey @CodeTorso 
- Great to see your enthusiasm towards this project 
- Let's discuss what colors would you chose for the selection when it is in light mode
- would you be able to implement that also? Given there's a theme toggle associated with this page

**Comment by CodeTorso** [comment]
Yes easily. btw which college are you in ? Do you believe going to college really helped you in programming ? just asking.

**Comment by warmachine028** [comment]
> Yes easily. btw which college are you in ? Do you believe going to college really helped you in programming ? just asking.

Going to college helped me build up my theory concepts in various CS subjects and programming in overall, but to polish the skills I had to do it myself and teach myself languages like JS, Python and other Frameworks.

Speaking of college, it is mentioned in my profile.

**Comment by CodeTorso** [comment]
Get active on twitter. It could really help you. In some fields even more than linkedIn also

**Comment by warmachine028** [comment]
You're still working on this issue right? You've mentioned the wrong issue in the merged PR

**Comment by CodeTorso** [comment]
Yes. I am working on it just taking little to get the right colours.
