### ISSUE TITLE
[FEATURE 💡] Better scrollbar for the website

### ISSUE THREAD

**Issue by CodeTorso** [warmachine028/nike#40]
### Description

Default browser scrollbar is not perfect.

We can make it much more appealing

**Comment by warmachine028** [comment]
Alright, this can be done but please provide some screenshots before I assign this to you.

**Comment by CodeTorso** [comment]
I will make a PR along with screenshots there. Just merge it if you like ok

**Comment by warmachine028** [comment]
Why did you close this issue, if you want to contribute to it?

**Comment by CodeTorso** [comment]
I am making a PR along with screenshots to get this issue done no more need to get here. If you like the PR merge it

**Comment by CodeTorso** [comment]
Sorry if it isn't how your repo code of conduct works.

**Comment by warmachine028** [comment]
> Sorry if it isn't how your repo code of conduct works.

It's okay, no big deal.
