### ISSUE TITLE
[Feature 💡] Enhance Landing Page with Animated Number Counters

### ISSUE THREAD

**Issue by ayushichoudhary-19** [warmachine028/nike#48]
## Description:
- The landing page currently appears static upon loading. 
- To enhance the user experience, I propose adding animated number counters to the displayed counts.
- This will not only make the page more dynamic but also draw attention to these key metrics.

## Screenshots

![image](https://github.com/warmachine028/nike/assets/73214455/135bb05d-9a94-4619-9328-0eeed73ef1cf)

## Suggestion:

Integrate animated number counters for metrics on the landing page. When a user visits the page, the numbers should increment smoothly from zero to their respective values.

## Why This Enhancement:

Animated counters can capture users' attention, provide a sense of interactivity, enhance the page's aesthetics, and add dynamism to the user experience.

#### I would appreciate feedback from the moderators and the community on the desirability of this enhancement. If it aligns with the project's goals and vision, I am excited to contribute and make this improvement myself.

**Comment by Sky-De** [comment]
@ayushichoudhary-19 hi, I would like to work on this, please assign this to me
Thanks

**Comment by warmachine028** [comment]
# Hello @Sky-De, great to see your enthusiasm towards contributing to nike
However someone is already working in this issue, I'd suggest you to 
- Find other ways to improve or add something new to this website, then create a new issue and get assigned.
- Wait for new issues to be created by the maintainers.
- Give them some time, if they are unable to solve this, you will get assigned.

## Meanwhile you can
- Visit the website to find scopes of improvement.
- Visit my other projects at [here](https://github.com/warmachine028/repositories)
- Follow me for more new projects
- Star 🌟 🌟 this project for future opportunities.

**Comment by ayushichoudhary-19** [comment]
@warmachine028 Please review the PR: https://github.com/warmachine028/nike/pull/52

**Comment by warmachine028** [comment]
Sorry, I had been busy with some other project. I have added my review and merged your PR.
Btw the work was fantastic.

**Comment by ayushichoudhary-19** [comment]
Thankyou for the appreciation! 
Sorry if I was being impatient. I'm new to Open Source and contributed to a react+tailwind css codebase for the first time so I had to struggle a bit to understand the codebase initially. The delay in the response made me wonder if my PR had some isssues and I got anxious.
