### ISSUE TITLE
[BUG 🐞] Enhance Input Field Design and Add Active State Effect

### ISSUE THREAD

**Issue by ayushichoudhary-19** [warmachine028/nike#49]
## Description:
The current design of the input field background on the website has several issues that affect the overall aesthetics and user experience. Specifically, the black bg stands out in a way that doesn't align with the website's visual style. There are inconsistencies in how the input field is presented in light mode and dark mode. Additionally, introducing an interactive effect when the input field is active can enhance the user experience.

## Issues:

**Inconsistent Background of Input Field:** The black background of the input field does not blend well with the overall aesthetics of the website, making it appear out of place.

## Inconsistencies in Mode Switching:

In dark mode, the entire input container is black.
In light mode, the typing area's background is set to black and rest of the container is white.

## Screenshots
![image](https://github.com/warmachine028/nike/assets/73214455/75b690f9-08b6-4b70-80fc-ffe823aae23a)

![image](https://github.com/warmachine028/nike/assets/73214455/a68b333e-4913-4ea8-8c3d-9b6b96e3ca53)

Border Style: The input field's sharp-edged black background contrasts with the rounded borders of the box covering the input field, resulting in an unpleasing visual inconsistency.

## Suggested Improvements:

Consider adjusting the background color to better match the website's color scheme and aesthetics.
Ensure consistency in the appearance of the input field between light and dark modes. 

#### I would like to raise this issue and offer my assistance in implementing the suggested improvements. If the community and moderators find these enhancements desirable, I am willing to contribute to the resolution of this issue.

**Comment by ayushichoudhary-19** [comment]
Well it appears that the issue is specific to screens with a width greater than or equal to 640px. 
Seems fine on smaller screens.
![image](https://github.com/warmachine028/nike/assets/73214455/0b105c65-e53d-4544-923a-9504ac7f94ed)


However, I would still wait for the feedback and the assignment for this issue.

**Comment by warmachine028** [comment]
Can you make it white for light theme, then I can assign you

**Comment by ayushichoudhary-19** [comment]
Yeah sure! @warmachine028

**Comment by warmachine028** [comment]
Assigning you

**Comment by warmachine028** [comment]
Make PR's seperately for both the issues.

**Comment by ayushichoudhary-19** [comment]
@warmachine028 please review the PR : https://github.com/warmachine028/nike/pull/51
