### ISSUE TITLE
[FEATURE 💡] Add a go to top FAB for Nike 

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#53]
### Description

- A floating action Button must be added to reach to top of the page on one click.
- This button must only be visible after reaching a certain height in the page from Top.
- The scroll effect must be smooth and not instant.
- It must be overlayed and the position must be at bottom right corner of the screen
- It must be visible for both small screen and large screen devices.

### Screenshots

- This is a reference of a Floating Action Button.
![IMG_20230913_121204](https://github.com/warmachine028/nike/assets/75939390/bcadf421-f1d2-4335-bd58-69264af553e9)

### Additional information

- Only use TailwindCSS and refrain from using Inline styles or Plain CSS.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by ayushichoudhary-19** [comment]
I can do it!

**Comment by warmachine028** [comment]
Assigning you

**Comment by warmachine028** [comment]
@ayushichoudhary-19 what's the status of this issue?

**Comment by ayushichoudhary-19** [comment]
I'll be done by tonight.

**Comment by warmachine028** [comment]
okay

**Comment by ayushichoudhary-19** [comment]
done: https://github.com/warmachine028/nike/pull/54
