### ISSUE TITLE
[BUG 🐞] Enhance the sidebar for mobile 

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#56]
### Description

- The side bar has a scope for improvement
- Add animations for opening
- Add a blur effect in the background.
- Add a better background color to match the site.
- Remove the Boolean value from the top left corner
- Use proper icons for closing and links instead of `X` and `>`

### Screenshots

![Screenshot_2023-09-19-01-41-21-279_com android chrome-edit](https://github.com/warmachine028/nike/assets/75939390/a801c571-ec6b-467f-81e6-bde5043749f1)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Sky-De** [comment]
@warmachine028 hi, i would like to work on this, please assign this to me
Thanks

**Comment by warmachine028** [comment]
Assigning you, hope you learn something from it
