### ISSUE TITLE
[BUG 🐞] typo class declaration at sections PopularProducts.jsx

### ISSUE THREAD

**Issue by gonsura** [warmachine028/nike#63]
### Description

typo class declaration at sections PopularProducts.jsx  line 16

sm-grid-cols-2 maybe sm:grid-cols-2

### Screenshots

<img width="959" alt="Screenshot 2023-09-21 222923" src="https://github.com/warmachine028/nike/assets/121378129/11fa08b4-01fa-44e0-87ab-d22312fb126f">

**Comment by warmachine028** [comment]
Extremely sorry, for late response. I was too busy in college work. Assigning you right away
