### ISSUE TITLE
[FEATURE 💡] Search Bar

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#66]
### Description

- This site needs a simple search bar at the top of the page.
- The search bar must match the overall aesthetics of the page
- The UI is to be added for now.
- A separate issue will be created to add functionality later

## Desktop View

![image](https://github.com/warmachine028/nike/assets/75939390/110a4a33-e413-4f36-8e03-b5d19a12014c)

## Mobile view
- default
![image](https://github.com/warmachine028/nike/assets/75939390/651cfb32-fc69-4cfb-86ee-9d40b01b6f9b)

- When clicked
![image](https://github.com/warmachine028/nike/assets/75939390/904507eb-6aad-47b1-ad25-7a3ec8d99c7a)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Ehsan-Yari** [comment]
Hey @warmachine028.
I want to contribute to this project. This open issue aligns with my skills and interests. If it's possible, could you kindly consider assigning this task to me? Thank you.

**Comment by warmachine028** [comment]
@Ehsan-Yari assigning you

**Comment by warmachine028** [comment]
@Ehsan-Yari please start working on the issue soon

**Comment by Ehsan-Yari** [comment]
@warmachine028 thank you i just started working on it
