### ISSUE TITLE
[FEATURE 💡] Remove Nike from header in mobile devices

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#67]
### Description

- Remove the nike text from the logo **(Only for mobile devices)**
- Make the navbar a bit shorter for **(Only for mobile devices)**
- The logo and icons must also be made smaller 
- The theme icon seems not aligned properly
- Take reference from the original site webpage screenshots given below

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/8a94beb9-fbcc-40fd-bdce-b094aa5d8a6c)

- Reference
![image](https://github.com/warmachine028/nike/assets/75939390/4e4d01c0-3631-40a5-a03b-99b42cf5c285)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by sahilrw** [comment]
Hey @warmachine028.
I'm eager to contribute to this project. This open issue aligns with my skills and interests. If it's possible, could you kindly consider assigning this task to me? I would be grateful for the opportunity to contribute to the project. Thank you.

**Comment by warmachine028** [comment]
## Okay! @sahilrw I have assigned you to this issue
- Make sure to consult if any confusion arises before making a Pull Request.
- I might not be available instantly, but I will address your confusion
- Make sure to complete all the tasks in the Description above
- Take reference from other closed PR to fill the Pull Request template
- The title of your PR must be same as this issue

**Comment by sahilrw** [comment]
Thank you.

**Comment by warmachine028** [comment]
@sahilrw, please start working on this issue soon

**Comment by sahilrw** [comment]
I am having trouble removing the text from the logo. Any suggestions as to how I can do that?
Everything else is completed.

**Comment by warmachine028** [comment]
I believe the text and logo are 1 single segment, what if we display only the logo, the logo is available at this path

**Comment by sahilrw** [comment]
Yes. That is doable. Will get it done asap.

**Comment by mehulrnsit** [comment]
Would Like to take up this issue if not been closed yet

**Comment by warmachine028** [comment]
Yes the issue is open

**Comment by 7Priyanshu9** [comment]
would like to contribute if its still open

**Comment by warmachine028** [comment]
Someone is already assigned, please find some other ways to contribute to the project. If he's unable to solve this issue you will be assigned soon.

**Comment by warmachine028** [comment]
Hey @mehulrnsit could you please check if the Merged PR is showing in your [hacktoberfest profile](https://hacktoberfest.com/profile) in Progress or not?


Example: 

![image](https://github.com/warmachine028/nike/assets/75939390/3dd78ee3-4a3f-4b2e-91a2-2fd8ec4cd061)
