### ISSUE TITLE
[FEATURE 💡] Add Email validation during newsletter signup

### ISSUE THREAD

**Issue by rakimsth** [warmachine028/nike#72]
### Description

Currently there is no visible email validation warning in the sign up section. Can we implement the basic email validation rule using yup.

### Screenshots

![image](https://github.com/warmachine028/nike/assets/23047979/690eb3c8-82eb-4fda-a07f-5582af75ae39)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
Assigning you

**Comment by warmachine028** [comment]
@rakimsth, please start working on this issue

**Comment by rakimsth** [comment]
@warmachine028 , Sure let me wrap this up within this weekend

**Comment by warmachine028** [comment]
@rakimsth what is the progress?

**Comment by rakimsth** [comment]
@warmachine028 , Sending PR today. Wrapped up the validation

**Comment by warmachine028** [comment]
@rakimsth have you solved this?

**Comment by rakimsth** [comment]
@warmachine028 , Yes, sending PR
On Wrong Email Address Input :
<img width="1458" alt="image" src="https://github.com/warmachine028/nike/assets/23047979/11533644-b51e-4c97-acd4-3f0867fd4c4b">

On Correct Email Address Input: 
<img width="1467" alt="image" src="https://github.com/warmachine028/nike/assets/23047979/5b9f9891-3ede-40dd-a38b-1b7c884685f0">
