### ISSUE TITLE
[DOCS 📄] Best Contributors

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#76]
### Description

- Currently on clicking the best contributor's icons in [README.md](https://github.com/warmachine028/nike/tree/main/README.md), it takes to the project's [contributor page](https://github.com/warmachine028/nike/graphs/contributors).
- It would be nice if we could redirect each icon links to individual contributor's profile instead.
- This issue must be implemented without changing the current style.
- The contributor's must not be added manually in the README.md rather they must be dynamically added as currently.

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/69dff60b-965b-4993-b94a-98affd89ad83)

**Comment by devmusiczz** [comment]
Hey @warmachine028 can you please assign this issue to me? I'd like to work on this issue.

**Comment by warmachine028** [comment]
Sure if you have any idea how to fix it, then go ahead.
Assigning you right away.

**Comment by devmusiczz** [comment]
I could be wrong but if we have to dynamically change the contributors rather than changing them manually, this must not categorised as a good first issue.

**Comment by warmachine028** [comment]
Have you progressed any further?

**Comment by devmusiczz** [comment]
hey, I've researched and checked that , it can be done using GitHub actions. but it doesn't seems like a good First issue. I'm a beginner still i tried my best to achieve that but can't able to meet the expectations. I'm so sorry.

**Comment by warmachine028** [comment]
It was enough that you tried, at least you learned something new.

**Comment by Pinaka-Pani-18** [comment]
Hi, Can I work on this issue ?

**Comment by warmachine028** [comment]
How do you aim to solve this?

**Comment by TomerPacific** [comment]
@warmachine028  - I think this can be solved by manually linking each profile image to the person's github page. Let me know if you would like me to fix this.

**Comment by warmachine028** [comment]
I believe I should close this issue if this is the only available solution for now.
