### ISSUE TITLE
[DOCS 📄] Page link to icon

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#77]
### Description

- Currently on clicking the icon of README.md, it opens the icon itself.
- The link tag must be fixed to redirect to the original deployed Nike website.

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/72f2e19c-9f47-4409-a4b6-9007cda2ea09)

**Comment by Swarno-Coder** [comment]
@warmachine028 @AdityaAB4 @vaqueraoscar0 @ayushichoudhary-19 @Sky-De  can I work on this issue? Assign me

**Comment by warmachine028** [comment]
- Sure, you can work on it.

**Comment by Anirudha0702** [comment]
@warmachine028 can I work on this issue? Assign me

**Comment by warmachine028** [comment]
@Anirudha0702 someone is already working on this issue, see if you can find other ways to contribute. Then raise a new issue

**Comment by warmachine028** [comment]
I have assigned you both
