### ISSUE TITLE
[FEATURE 💡] Project Icon to be added in Footer

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#78]
### Description

- Add github icon in the footer
- Add this project link in the icon

### Screenshots

![image](https://github.com/warmachine028/nike/assets/75939390/911d3858-20d6-46dc-8f56-3d5e3673f967)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by chiku011** [comment]
can you assign this issue to me

**Comment by warmachine028** [comment]
sure

**Comment by warmachine028** [comment]
@chiku011 did you start working in it?
