### ISSUE TITLE
[BUG 🐞] Navbar is not present in shoe detail page

### ISSUE THREAD

**Issue by rakimsth** [warmachine028/nike#82]
### Description

The Navbar should persist when we visit different routes. Eg: When we go from home page to /shoe_detail page. But, there is no navbar in the detail page. Is this intentional?

### Screenshots

<img width="1500" alt="image" src="https://github.com/warmachine028/nike/assets/23047979/28eaa779-8be6-4457-b829-e62fd2097cf0">

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
Please work on it and add the original Navbar in the top. Assigning you
