### ISSUE TITLE
[BUG 🐞] Hamburger menu for View Details

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#90]
### Description

- Hamburger menu is hidden for shoe details page because the page links are for Home
- Add proper logic to display view details link and enable hamburger menu for Show Details Page.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Smit1610** [comment]
@warmachine028 Can you please assign this task to me ?

**Comment by warmachine028** [comment]
Sure, assigning

**Comment by Smit1610** [comment]
Is it issue with mobile device ?

**Comment by Smit1610** [comment]
can you please share some image/video what exactly the bug is ?

**Comment by warmachine028** [comment]
Go to mobile devices and see that the hamburger menu is not opening for the ShoeDetails page

**Comment by Smit1610** [comment]
![image](https://github.com/warmachine028/nike/assets/142035941/a0fcc6fb-1aec-442e-9264-aa39e307a463)
This hamburger menu us not opening write ?

**Comment by warmachine028** [comment]
Yes, start working on it

**Comment by warmachine028** [comment]
@Smit1610 will you be able to solve it?
