### ISSUE TITLE
[FEATURE 💡] Prettier Formatting for consistency

### ISSUE THREAD

**Issue by rakimsth** [warmachine028/nike#94]
### Description

Since we have lot of devs working on this project. We need to have prettier and husky setup for proper code formatting during git push. 

### Screenshots

Issues such as these can be avoided with uniform code formatting.
<img width="1115" alt="image" src="https://github.com/warmachine028/nike/assets/23047979/d6a63a57-a458-4214-951f-7084b04b104d">

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
Yes, please add this. Assigning you
