### ISSUE TITLE
[FEATURE 💡] Add Smooth Scrolling Through Navbar

### ISSUE THREAD

**Issue by Keshav-Aneja** [warmachine028/nike#95]
### Description

In the current version of our application, there is a noticeable issue when users click on navigation items. Instead of providing a seamless and user-friendly experience, the navigation causes a split scroll, which disrupts the overall usability and aesthetics of the website. This issue can be significantly improved by introducing the Smooth Scrolling functionality.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Keshav-Aneja** [comment]
Please assign this Issue to me!

**Comment by warmachine028** [comment]
Sure assigning you

**Comment by Keshav-Aneja** [comment]
@warmachine028 I have added a pull request for the Smooth Scrolling. Please Review and accept it. Thank You for giving me a chance to contribute.
